### ISSUE TITLE
How to use this with go-github v65?

### ISSUE THREAD

**Issue by marcofranssen** [enrichman/gh-iter#1]
I'm using the last go-github v65. That doesn't seem to work with this package as this package depends on go-github v63.

I have been trying with following:

```
replace github.com/google/go-github/v63 v63.0.0 => github.com/google/go-github/v65 v65.0.0
```

**Comment by enrichman** [comment]
Hi @marcofranssen, thanks for the issue and the PR.

So the replace doesn't work? I'm thinking about a versioning strategy to cope with the `go-github` versions, and the library.

**Comment by marcofranssen** [comment]
Probably best would be if this thing would become available as a package in the go-github library itself as it is tightly coupled with the version of go-github.

Now basically your module needs an update before someone can bump to the new go-github release.

Have you thought about contributing this to go-github?

**Comment by enrichman** [comment]
> Probably best would be if this thing would become available as a package in the go-github library itself as it is tightly coupled with the version of go-github.
> 
> Now basically your module needs an update before someone can bump to the new go-github release.
> 
> Have you thought about contributing this to go-github?

Sorry for the late reponse. Yes, I opened an [issue](https://github.com/google/go-github/issues/3209) before the 1.23 became stable and together with @gmlewis we decided to add this to the README to test if it could be an interesting feature to have.

If you find it interesting it will worth to have a comment in that issue, or opening a new one mentioning the package!

**Comment by enrichman** [comment]
Tagged v65! Closing this. :)
